//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avicola.Sales.Entities
{
    using System;
    
    public partial class DepositStock
    {
        public System.Guid ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Boxes { get; set; }
        public Nullable<int> Maples { get; set; }
        public Nullable<int> Eggs { get; set; }
    }
}
