CREATE TABLE [dbo].[Barn](
	[Id] [uniqueidentifier] NOT NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
	[Number] [int] NOT NULL,
	[Capacity] [int] NULL,
	[StageId] [uniqueidentifier] NOT NULL DEFAULT '096DEBD6-C537-4569-8B97-53A3C3E82A39',
	[IsDeleted] BIT NOT NULL DEFAULT 0, 
    CONSTRAINT [PK_Barn] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY], 
    CONSTRAINT [FK_Barn_Stage] FOREIGN KEY ([StageId]) REFERENCES [Stage]([Id]),

) ON [PRIMARY]
