CREATE TABLE [dbo].[Barn](
	[Id] [uniqueidentifier] NOT NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
	[Number] [int] NOT NULL,
	[Capacity] [int] NULL,
	[IsDeleted] BIT NOT NULL DEFAULT 0, 
    CONSTRAINT [PK_Barn] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
