//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avicola.Office.Entities
{
    using System;
    using System.Collections.Generic;
    
    using Framework.Data.Interfaces;
    public partial class BatchMedicine : IEntity
    {
        public System.Guid Id { get; set; }
        public System.Guid BatchId { get; set; }
        public System.Guid MedicineId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsDeleted { get; set; }
        public string Observation { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
