//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avicola.Office.Entities
{
    using System;
    using System.Collections.Generic;
    
    using Framework.Data.Interfaces;
    public partial class BatchBarn : IEntity
    {
        public System.Guid Id { get; set; }
        public System.Guid BatchId { get; set; }
        public System.Guid BarnId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int InitialBirds { get; set; }
        public decimal StartingFood { get; set; }
        public System.Guid FoodClassId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Barn Barn { get; set; }
        public virtual FoodClass FoodClass { get; set; }
        public virtual Batch Batch { get; set; }
    }
}
