//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avicola.Office.Entities
{
    using System;
    
    public partial class ReportBreedingMeasuresFollowUpRow
    {
        public Nullable<int> Semana { get; set; }
        public Nullable<int> Dia { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Secuencia { get; set; }
        public Nullable<int> Mortandad { get; set; }
        public Nullable<int> Descarte { get; set; }
        public Nullable<int> TotalEliminado { get; set; }
        public Nullable<int> Aves { get; set; }
        public Nullable<decimal> PesoDelAve { get; set; }
        public Nullable<decimal> IngresoAlimento { get; set; }
        public string ClaseAlimento { get; set; }
        public Nullable<decimal> IngresoAlimentoAcumulado { get; set; }
        public Nullable<decimal> ConsumoAlimento { get; set; }
        public Nullable<decimal> ConsumoAlimentoAcumulado { get; set; }
        public Nullable<int> ConsumoPorAve { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public string Mes { get; set; }
        public Nullable<int> DiaDelMes { get; set; }
        public string FechaNacimiento { get; set; }
        public Nullable<int> Lote { get; set; }
        public string LineaGenetica { get; set; }
        public string Clase { get; set; }
        public Nullable<int> AvesAlInicio { get; set; }
        public Nullable<decimal> AlimentoAlInicio { get; set; }
        public Nullable<decimal> ConsumoRealPorAve { get; set; }
        public Nullable<decimal> AlimentoInicialMes { get; set; }
        public Nullable<decimal> ConsumoTotalMes { get; set; }
        public Nullable<decimal> ConsumoDiario { get; set; }
    }
}
