//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avicola.Office.Entities
{
    using System;
    using System.Collections.Generic;
    
    using Framework.Data.Interfaces;
    public partial class StageChange : IEntity
    {
        public System.Guid Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid BatchId { get; set; }
        public System.Guid StageFromId { get; set; }
        public System.Guid StageToId { get; set; }
        public int StageFromInitialBirds { get; set; }
        public decimal FoodEntryDuringPeriod { get; set; }
        public decimal CurrentFoodStock { get; set; }
        public bool IsDeleted { get; set; }
        public int StageFromIFinalBirds { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Stage StageFrom { get; set; }
        public virtual Stage StageTo { get; set; }
    }
}
