//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avicola.Office.Entities
{
    using System;
    using System.Collections.Generic;
    
    using Framework.Data.Interfaces;
    public partial class Standard : IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Standard()
        {
            this.StandardGeneticLines = new HashSet<StandardGeneticLine>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Name { get; set; }
        public System.Guid DataLoadTypeId { get; set; }
        public bool IsDeleted { get; set; }
        public string MeasureUnity { get; set; }
        public System.Guid StandardTypeId { get; set; }
        public bool AllowDecimal { get; set; }
        public string AggregateOperation { get; set; }
        public int YAxis { get; set; }
        public Nullable<int> DivideChartWeek { get; set; }
        public Nullable<int> StartingWeek { get; set; }
    
        public virtual DataLoadType DataLoadType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StandardGeneticLine> StandardGeneticLines { get; set; }
        public virtual StandardType StandardType { get; set; }
    }
}
