//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Avicola.Sales.Entities;

namespace Avicola.Sales.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SalesEntities : DbContext
    {
        public SalesEntities()
            : base("name=SalesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Deposit> Deposits { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<StockEntry> StockEntries { get; set; }
        public virtual DbSet<Truck> Trucks { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderStatus> OrderStatuses { get; set; }
        public virtual DbSet<Classification> Classifications { get; set; }
        public virtual DbSet<ClassificationEggClass> ClassificationEggClasses { get; set; }
        public virtual DbSet<EggClass> EggClasses { get; set; }
        public virtual DbSet<EggEquivalence> EggEquivalences { get; set; }
        public virtual DbSet<OrderEggClass> OrderEggClasses { get; set; }
    
        public virtual ObjectResult<DepositStock> StockGetByDeposit(Nullable<System.Guid> depositId)
        {
            var depositIdParameter = depositId.HasValue ?
                new ObjectParameter("DepositId", depositId) :
                new ObjectParameter("DepositId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DepositStock>("StockGetByDeposit", depositIdParameter);
        }
    
        public virtual ObjectResult<EggClassStock> StockGetByEggClass(Nullable<System.Guid> depositId)
        {
            var depositIdParameter = depositId.HasValue ?
                new ObjectParameter("DepositId", depositId) :
                new ObjectParameter("DepositId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EggClassStock>("StockGetByEggClass", depositIdParameter);
        }
    }
}
